// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatedClassFlight : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedClassFlight));
        
        string IMigrationMetadata.Id
        {
            get { return "202203061058121_updatedClassFlight"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
